name: Flutter Build

on: [push]

jobs:
  build:
    name: flutter build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.x'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test --coverage
